name: ğŸ§ª Test with coverage ğŸ“Š

on:
  workflow_call:

jobs:
  coverage:
    name: ğŸ§ª Test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: â¬‡ï¸ Checkout repository
        uses: actions/checkout@v3

      - name: âš™ï¸ Install lcov
        run: |
          sudo apt-get update
          sudo apt-get -y install lcov

      - name: âš™ï¸ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: âš™ï¸ Flutter pub get
        run: flutter pub get

      - name: ğŸ§ª Run tests with coverage
        run: |
          chmod +x scripts/*.sh
          ./scripts/test-with-coverage.sh

      - name: ğŸ§ªâœ…âŒ Publish test results
        id: compute_test_results
        uses: dorny/test-reporter@v2.5.0
        with:
          name: "ğŸ§ªğŸ“Š Unit tests report"
          path: test_reports/*_test_report.json
          reporter: "flutter-json"
          max-annotations: "50"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸªª Create passing test results badge
        if: github.event_name == 'push' && github.event.ref == 'refs/heads/main'
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.BADGE_GIST_TOKEN }}
          gistID: "a326af0439aec9c2a4aed809dc731a36"
          filename: "passing-tests-badge.json"
          label: "Tests"
          message: "${{ steps.compute_test_results.outputs.passed }} passed, ${{ steps.compute_test_results.outputs.failed }} failed"
          namedLogo: "TestCafe"
          labelColor: "lightgrey"
          color: ${{ steps.compute_test_results.outputs.failed == 0 && 'brightgreen' ||  'red' }}

      - name: ğŸ§ªğŸ“Š Publish coverage report
        if: github.event_name == 'pull_request'
        uses: romeovs/lcov-reporter-action@v0.4.0
        with:
          lcov-file: coverage_report/cleaned_combined_lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
          title: "Coverage Report"
